{{- $fullName := include "vaultstadio.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secrets
  labels:
    {{- include "vaultstadio.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.backend.env.VAULTSTADIO_JWT_SECRET | default (randAlphaNum 32) | b64enc | quote }}

{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-postgresql
  labels:
    {{- include "vaultstadio.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
